version: "3.2"
services:
  tedx-web:
    image: lukify13/tedxmec-website:1.1
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - VIRTUALPORT=5173
      - VIRTUAL_HOST=tedx.mec.ac.in
networks:
  default:
    external:
      name: mec